---
- name: Install firewall and fail2ban
  apt: name="{{ item }}" state=present force=yes
  with_items:
    - iptables
    - fail2ban
    - whois

- name: Configure fail2ban
  template: src=jail.local.j2 dest=/etc/fail2ban/jail.local owner=root group=root mode=644
