---
- name: Install ntpdate
  apt: name=ntpdate state=present force=yes

- name: Set timezone to Europe/Amsterdam
  file: src='/usr/share/zoneinfo/Europe/Amsterdam' dest=/etc/localtime state=link force=yes

- name: Update tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: Sync with XS4ALL NTP server
  command: ntpdate ntp.xs4all.nl
