---
- name: Install packages
  apt: name="{{ item }}" state=latest force=yes
  with_items:
    - chromium-browser
    - unclutter
    - ttf-mscorefonts-installer
    - cabextract
    - fontconfig

- name: Make dir for fonts
  file:
    path: /home/pi/.fonts
    state: directory
    mode: 0755
    owner: pi
    group: pi

- name: Get Cleartype fonts
  get_url:
    url: http://plasmasturm.org/code/vistafonts-installer/vistafonts-installer
    dest: /etc/fonts-installer
    owner: pi
    group: pi

- name: Install Cleartype fonts
  script: /etc/fonts-installer

- name: Clean old Chrome installs
  lineinfile:
    path: /etc/xdg/lxsession/LXDE-pi/autostart
    regexp: '^chromium-browser'
    state: absent

- name: Enable fullscreen Chrome
  lineinfile:
    path: /etc/xdg/lxsession/LXDE-pi/autostart
    line: "chromium-browser {{ chrome_url }}  --incognito --kiosk --disable-dialogs --noerrdialogs --disable-session-crashed-bubble --disable-infobars"

- include: screensetup.yml
