---
- name: Install packages
  apt: name="{{ item }}" state=latest force=yes
  with_items:
    - chromium-browser
    - unclutter
    - ttf-mscorefonts-installer

- name: Disable screensaver
  lineinfile:
    path: /etc/xdg/lxsession/LXDE-pi/autostart
    line: "{{ item }}"
  with_items:
    - "@xset s noblank"
    - "@xset s off"
    - "@xset -dpms"

- name: Clean old Chrome installs
  lineinfile:
    path: /etc/xdg/lxsession/LXDE-pi/autostart
    regexp: '^chromium-browser'
    state: absent

- name: Enable fullscreen Chrome
  lineinfile:
    path: /etc/xdg/lxsession/LXDE-pi/autostart
    line: "chromium-browser {{ chrome_url }}  --incognito --kiosk --disable-dialogs --noerrdialogs --disable-session-crashed-bubble --disable-infobars"

- include: screensetup.yml
