---
- name: Install packages
  apt: name="{{ item }}" state=latest force=yes
  with_items:
    - chromium-browser
    - unclutter
    - ttf-mscorefonts-installer
    - fonts-crosextra-carlito
    - fonts-crosextra-caladea

- name: Clean old Chrome installs
  lineinfile:
    path: /etc/xdg/lxsession/LXDE-pi/autostart
    regexp: '^chromium-browser'
    state: absent

- name: Enable fullscreen Chrome
  lineinfile:
    path: /etc/xdg/lxsession/LXDE-pi/autostart
    line: "chromium-browser {{ chrome_url }}  --incognito --kiosk --disable-dialogs --noerrdialogs --disable-session-crashed-bubble --disable-infobars"

- include: screensetup.yml
